### ISSUE TITLE
AMD invalid results no valid at all, lacks any other logs, hashrate is good, how to find problem?

### ISSUE THREAD

**Issue by nikolobok** [fireice-uk/xmr-stak#1683] opened 2018-06-28 12:49 UTC

**Comment by Spudz76** [comment] 2018-06-29 09:54
Probably by describing your hardware and software and what pool/coin, at a minimum.

**Comment by nikolobok** [comment] 2018-06-29 17:01
Vega FE x3, Fedora 27, rocm + amdgpu-pro 18.20, monero7, nanopool
But is there some more verbose logging?

**Comment by whompy** [comment] 2018-06-29 21:06
For clarification, I'm experiencing an issue where I see my GPU providing hashes via the logs and web interface, but pools aren't receiving the hashes. I get no accepted nor rejected shares. @nikolobok, if this is what you're referencing, I can grab package and system info in this ticket. Otherwise I'll create a new issue tonight.

**Comment by whompy** [comment] 2018-06-30 12:16
Rejected hashes by pool is typically an issue stemming from the wrong
algorithm being selected. My issue turned out to be easily resolved by
turning off caching (--noAMDCache).

**Comment by Spudz76** [comment] 2018-06-30 13:59
There is more output if you compile and select Debug
Generally network you would just use tcpdump or wireshark and capture filter for pool traffic by ip or port.
`tcpdump -i eth0 -vv -s0 -A 'host xmr-us-west1.nanopool.org'` for example

**Comment by nikolobok** [comment] 2018-06-30 17:08
@Spudz76 Did not seen any shares sent to pool, only empty packets (length=0), seems ACK packages.
also no any additional log with CMAKE_BUILD_TYPE=Debug option
so "AMD invalid results" - not about rejected shares by pool...
any ideas?

**Comment by Spudz76** [comment] 2018-07-01 00:11
What's your clinfo look like?

**Comment by dr-giani** [comment] 2018-07-01 02:47
@ Whompy
I have the same issue!
I have 1xRX460 and bought 2xRX550 to expand it to some low-end rig. I installed xmr-stak-2.4.5 with no problem.
Started xmr-stak, GPUs are recognized, CPU is recognized and, per xmr-stak, they are all mining (2xGPU: 2x300H/s & CPU:500H/s). Everything looks good.
But, hash-rate reported by pool is way off. I know that they do not match exactly, but over some time they should even out and get close. This was not the case. Hash-rate difference between pool and xmr-stak remained. And pool doesn’t seem to be a problem (pool stat matches CPU & RX460, but with RX550 it is off).
So, I played with different versions of kubuntu and different amdgpu-pro drivers, thinking that the problem is there.
Finally, after some time, I think I nailed down the problem… I started ‘disconnecting’ each of components: CPU, RX460 & RX550. The way I did is editing cpu.txt file (using option ‘null’ instead of cpu_threads_conf) and amd.txt file (deleting ‘gpu_threads_conf’ for card I didn’t want to mine).
So, doing that, I had CPU only giving 500H/s, RX460 only giving 300H/s. And combined they worked (and still work) for 800H/s. That was confirmed in pool stat (fairly close over some time).
And making only RX550 work did not give any hash-rate reported by the pool (and, later, when I started RX460 again, pool stat showed hashes, so this is not the pool issue). At that point, xmr-stak kept showing 300H/s, pool hash-rate stat was dropping and difficulty in xmr-stack was also dropping. Fairly quickly (5-10min) I had pool stat showing 2H/s, and xmr-stack showing 300H/s with difficulty of 100.
And, that is the problem I see as a user.
I am pretty positive that the issue is not with the pool – looks like pool sees no hashes and drops down difficulty (if it works that way).
XMR-stak thinks it generates hashes, but they are not sent to the pool. Or, maybe it was not generating anything, since GPU remained cool. On the other side, it has feedback from the pool through minimized difficulty, and it shows / recognizes that.
And, maybe the problem is with amdgpu-pro driver and communication between xmr-stak and gpu.
Not sure how to resolve this. Any help is appreciated.

**Comment by dr-giani** [comment] 2018-07-01 02:58
Forgot to say... Kubuntu 18.04, MD-APP-SDK-v3.0.130.136-GA-linux64, amdgpu-pro-18.20-606296 (legacy, headless) & xmr-stak-2.4.5.
And, I do not think that hashes are rejected by the pool... somehow they are not getting to the pool...
since gpu is completely cool, I think hashes are not even generated... 
LOL - what a computer expertise - gpu temperature is low, so it is not mining :)

clinfo for RX460 (that works) & RX550 (not working) are below

Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (2639.3)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:                                 AMD Accelerated Parallel Processing
Number of devices:                               2
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    AMD Radeon (TM) RX 460 Graphics
  Device Topology:                               PCI[ B#8, D#0, F#0 ]
  Max compute units:                             14
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1200Mhz
  Address bits:                                  64
  Max memory allocation:                         1665517363
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            2205962240
  Constant buffer size:                          1665517363
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            0
  Max pipe active reservations:                  0
  Max pipe packet size:                          0
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     0
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:                              
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:                                
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:                              
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:                            
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   0x7effcf2059f0
  Name:                                          Baffin
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 1.2 
  Driver version:                                2639.3
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2639.3)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 


  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Radeon 550 Series
  Device Topology:                               PCI[ B#9, D#0, F#0 ]
  Max compute units:                             8
  Max work items dimensions:                     3
    Max work items[0]:                           1024
    Max work items[1]:                           1024
    Max work items[2]:                           1024
  Max work group size:                           256
  Preferred vector width char:                   4
  Preferred vector width short:                  2
  Preferred vector width int:                    1
  Preferred vector width long:                   1
  Preferred vector width float:                  1
  Preferred vector width double:                 1
  Native vector width char:                      4
  Native vector width short:                     2
  Native vector width int:                       1
  Native vector width long:                      1
  Native vector width float:                     1
  Native vector width double:                    1
  Max clock frequency:                           1183Mhz
  Address bits:                                  64
  Max memory allocation:                         1676954419
  Image support:                                 Yes
  Max number of images read arguments:           128
  Max number of images write arguments:          8
  Max image 2D width:                            16384
  Max image 2D height:                           16384
  Max image 3D width:                            2048
  Max image 3D height:                           2048
  Max image 3D depth:                            2048
  Max samplers within kernel:                    16
  Max size of kernel argument:                   1024
  Alignment (bits) of base address:              2048
  Minimum alignment (bytes) for any datatype:    128
  Single precision floating point capability
    Denorms:                                     No
    Quiet NaNs:                                  Yes
    Round to nearest even:                       Yes
    Round to zero:                               Yes
    Round to +ve and infinity:                   Yes
    IEEE754-2008 fused multiply-add:             Yes
  Cache type:                                    Read/Write
  Cache line size:                               64
  Cache size:                                    16384
  Global memory size:                            2235195392
  Constant buffer size:                          1676954419
  Max number of constant args:                   8
  Local memory type:                             Scratchpad
  Local memory size:                             32768
  Max pipe arguments:                            0
  Max pipe active reservations:                  0
  Max pipe packet size:                          0
  Max global variable size:                      0
  Max global variable preferred total size:      0
  Max read/write image args:                     0
  Max on device events:                          0
  Queue on device max size:                      0
  Max on device queues:                          0
  Queue on device preferred size:                0
  SVM capabilities:                              
    Coarse grain buffer:                         No
    Fine grain buffer:                           No
    Fine grain system:                           No
    Atomics:                                     No
  Preferred platform atomic alignment:           0
  Preferred global atomic alignment:             0
  Preferred local atomic alignment:              0
  Kernel Preferred work group size multiple:     64
  Error correction support:                      0
  Unified memory for Host and Device:            0
  Profiling timer resolution:                    1
  Device endianess:                              Little
  Available:                                     Yes
  Compiler available:                            Yes
  Execution capabilities:                                
    Execute OpenCL kernels:                      Yes
    Execute native function:                     No
  Queue on Host properties:                              
    Out-of-Order:                                No
    Profiling :                                  Yes
  Queue on Device properties:                            
    Out-of-Order:                                No
    Profiling :                                  No
  Platform ID:                                   0x7effcf2059f0
  Name:                                          gfx804
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 1.2 
  Driver version:                                2639.3
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 1.2 AMD-APP (2639.3)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event

**Comment by cyborg00222** [comment] 2018-07-01 03:21
Hi!

I just reinstalled my Arch Linux, and now xmr-stak is only spitting out AMD Invalid Result GPU ID 0 errors. I'm now also on the new 18.20 driver. Maybe that changed something. I'll now try to get a older branch, and then I'm on my way to bed.

CPU is mining as usual.

Algorithm : monero7
Pool : supportxmr

#### clinfo : 
```
[acheloos@hadson miner]$ clinfo
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (2639.3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     Ellesmere
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2639.3)
  Driver Version                                  2639.3
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Board Name (AMD)                         Radeon RX 580 Series
  Device Topology (AMD)                           PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               36
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1350MHz
  Graphics IP (AMD)                               8.0
  Device Partition                                (core)
    Max number of sub-devices                     36
    Supported partition types                     (n/a)
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              8218742784 (7.654GiB)
  Global free memory (AMD)                        8006404 (7.636GiB)
  Global memory channels (AMD)                    8
  Global memory banks per channel (AMD)           16
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           4244635648 (3.953GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        4244635648 (3.953GiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1530414660999996936ns (Sun Jul  1 05:11:00 2018)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  Yes
    Number of async queues (AMD)                  2
    Max real-time compute queues (AMD)            0
    Max real-time compute units (AMD)             0
    SPIR versions                                 1.2
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
  clCreateContext(NULL, ...) [default]            Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Ellesmere
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Ellesmere
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Ellesmere

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
[acheloos@hadson miner]$ clinfo
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (2639.3)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     Ellesmere
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 AMD-APP (2639.3)
  Driver Version                                  2639.3
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     GPU
  Device Board Name (AMD)                         Radeon RX 580 Series
  Device Topology (AMD)                           PCI-E, 01:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               36
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1350MHz
  Graphics IP (AMD)                               8.0
  Device Partition                                (core)
    Max number of sub-devices                     36
    Supported partition types                     (n/a)
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64
  Preferred / native vector sizes                 
    char                                                 4 / 4       
    short                                                2 / 2       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (cl_khr_fp16)
    float                                                1 / 1       
    double                                               1 / 1        (cl_khr_fp64)
  Half-precision Floating-point support           (cl_khr_fp16)
    Denormals                                     No
    Infinity and NANs                             No
    Round to nearest                              No
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              8193073152 (7.63GiB)
  Global free memory (AMD)                        7981208 (7.611GiB)
  Global memory channels (AMD)                    8
  Global memory banks per channel (AMD)           16
  Global memory bank width (AMD)                  256 bytes
  Error Correction support                        No
  Max memory allocation                           4244635648 (3.953GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            134217728 pixels
    Max 1D or 2D image array size                 2048 images
    Base address alignment for 2D image buffers   256 bytes
    Pitch alignment for 2D image buffers          256 pixels
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Local memory syze per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
  Max number of constant args                     8
  Max constant buffer size                        4244635648 (3.953GiB)
  Preferred constant buffer size (AMD)            16384 (16KiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Profiling timer offset since Epoch (AMD)        1530414660999997707ns (Sun Jul  1 05:11:00 2018)
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Thread trace supported (AMD)                  Yes
    Number of async queues (AMD)                  2
    Max real-time compute queues (AMD)            0
    Max real-time compute units (AMD)             0
    SPIR versions                                 1.2
  printf() buffer size                            4194304 (4MiB)
  Built-in kernels                                (n/a)
  Device Extensions                               cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [AMD]
  clCreateContext(NULL, ...) [default]            Success [AMD]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Ellesmere
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Ellesmere
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 AMD Accelerated Parallel Processing
    Device Name                                   Ellesmere

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
```

**Comment by uentity** [comment] 2018-07-06 17:29
I have a similar problem with Vega on ROCm. I finally managed to start `xmr-stak` and it shows that work is being done (normal hashrate) and GPU temp rises, BUT no single valid share goes to the pool.

It seems like it calculating trash, verifies that it's a trash and keeps going forever. When I switch to AMDGPU-PRO 18.20, Vega starts finding valid shares.

But now I'm getting a SOCKET ERROR...

**Comment by Spudz76** [comment] 2018-07-06 20:58
Docs here need update, I may do so and submit the patches.

With 18.xx you *no longer need and should not install* (uninstall if installed) the AMD APP-SDK 3.0 and instead use the `opencl-amdgpu-pro-dev` package that comes with the new driver (but is not installed by the script).
With 17.xx you *do* need it, there is no dev package with the driver.
This must be why the APP-SDK disappeared off their site around when the first 18.xx was released.  There was no explanation from them, so we guessed.

Probably the APP-SDK compile, targeting 18.xx will have issues.
Probably the 17.xx works because it was compiled for APP-SDK, which is correct and proper.

In either case, you should link to the current driver `libOpenCL.so` and *not* the library from the SDK (you use the SDK with older than 17.xx literally only for the header files).  Check the CMakeCache.txt for the library location detected.  With 18.xx and no SDK installed, it will have no choice but to link to the driver (there is no dev library except in the driver package, perfect).

**Comment by chunk74** [comment] 2018-07-08 16:37
I've been messing around with this and I think that cyborg00222 is correct. This is likely an OpenCL version issue. Unfortunately, I've been unable to get the OpenCL and libDRM part of 17.40 to install alongside the 18.20 driver, so I can't verify what they did as fixing the issue.

However, I can verify that 18.20 amdgpu-pro-install with `opencl-amdgpu-pro-dev` and `ocl-icd-opencl-dev` loaded afterwards will get xmrstak to compile correctly and run with 100% invalid results.

Fresh Ubuntu 18.04 minimal install (4.15.0-23), PowerColor Red Devil RX 480

**Comment by Spudz76** [comment] 2018-07-09 15:13
`OpenCL 1.2 AMD-APP (2639.3)`

I have 2024 invalid results which based on total results 29021 is not every result (524 hours running)
This Tahiti is 25% of the rig hashrate so if every result was wrong it should be way worse than 9% invalid.
I was not happy about this invalid rate but it's also about the hackiest rig I have hardware wise, and it spews PCIe errors ("corrected") into dmesg pretty often so I figured it wasn't likely the software.  But also those errors are from a different slot.

So apparently this has been hitting me but not as bad, compiled with 18.20 and no SDK.
Reverting to 17.50 today I'm pretty sure that worked properly even with the crap hardware.  Then again the best rig I have is the Ubuntu 14 and fglrx 13 one, but that doesn't help with RX cards.

I have one RX480 in another rig with 18.20, but it has enough memory for Ethash so I don't run XMR on it ever, but ethminer has no issues and I compiled it the same general way.

What gcc version does 18.04 have?  Try with `clang-3.8` or newer...

**Comment by chunk74** [comment] 2018-07-10 03:33
Looks like gcc 7.3. I loaded clang 6.0 and tried to make it compile using clang, but it keeps picking up gcc as the compiler. Obviously, I could be doing something wrong here as I'm not very familiar with clang. 

In any event, I'm going to load Windows to see if I can get this system back up and mining. I had to move from 16.04 to 18.04 when my wifi card broke after a kernel update and it is supported out of the box on 18.04. 

As for the 100% invalid results, yeah I'm not running for an extended period. It could be that eventually it would generate valid results, but after 10 minutes or so of only generating invalid results. I gave up and started hacking on things.

**Comment by Spudz76** [comment] 2018-07-12 20:19
Yeah, I reverted to 17.50 and that Tahiti of mine has only chucked 2 bad results in days.

**Comment by yellatthewalls** [comment] 2018-07-20 04:10
im getting an amd invalid results for both of my gpus. when i booted the rig up today and ran stak, i got an opencl error and the file was missing from the folder. i redownloaded and setup and havent been able to get any valid results since. Im running XFX RX550 4GB with bios mods and overclocked. It was running stable before this.

**Comment by ITwrx** [comment] 2018-08-05 05:47
i'm using arch linux with radeon and opencl-amd. i have the same issue where xmr-stak reports normal hashes(5-600H/s each card), but pool shows 5-10h/s for each whole miner(x3). xmr-stak 2.4.4 and 2.4.7 exhibit this behavior. downgraded to 2.4.2 and all miners work fine again.

xf86-video-amdgpu 18.0.1-2
ocl-icd 2.2.12-1
opencl-amd 18.20.606296-1
opencl-headers 2:2.2.20170516-1

**Comment by dr-giani** [comment] 2018-08-19 05:40
I am using kubuntu 18.04 & xmr-stak-2.4.5.
The way i finally set it up is to install amdgpu-pro 16.60 driver first, compile xmr-stak and run it so amd.txt, config & cpu are generated.
Also, in /home/user/.openclcache/ there will be precompiled code files for OpenCl devices you are using.
Do not mess with precompiled files - keep them as they are, but uninstall amdgpu-pro 16.60 (if you leave this driver, kubuntu 18.04 would not boot up after restart - you will have to go boot it in the terminal).
Install amdgpu-pro 18.20 as explained in previous posts and start xmr-stak. It should work.

The way to check if gpus work is to use 'null' option in cpu.txt (so cpu does not mine; explained in cpu.txt) and to modify amd.txt, so you can use only certain gpu(s). With 'h' you can check hash rate (usually reported as everything works perfectly) & with 'r' you can get report where you can see how many good results you have and what is difficulty. You should have all good results with decent difficulty.
Seems that problem is with compiling code for OpenCL devices and amdgpu-pro 18.20 driver. I cannot tell why it happens, but 'my' workaround is explained above.
One more note... If you delete precompiled files from /home/user/.openclcache/ and compile them again (after running xmr-stak) with amdgpu-pro 18.20 installed, gpu(s) will not work.
Hope this helps.

**Comment by psychocrypt** [comment] 2018-08-19 09:39
Thx for the information. I am currently locking i to the rocm stack to
check whats going wrong. I ryn the amd driver 18.30 without any issues with
a rx570. On an other system with the rocm stack I also saw invalid shared.

**Comment by psychocrypt** [comment] 2018-10-05 20:48
Please check if #1866 solves you issue. If you use ROCm please update to ROCM 1.9

**Closed** 2018-10-05 21:01 UTC
