### ISSUE TITLE
Option to set specific pools configurations to specific devices

### ISSUE THREAD

**Issue by mojimi** [fireice-uk/xmr-stak#543] opened 2017-12-14 16:02 UTC
I find this is very useful if you want different gpus/cpus from the same rig mining to different addresses/pools. Not only to diversify but also if you're lending or sharing a specific device.

At the moment is quite an annoying workaround to do this, and goes against the whole "all-in-one".

So basically, an extra parameter in the devices configuration to choose specific pool config by id.

**Comment by tommy31** [comment] 2017-12-29 08:53
bump

**Comment by psychocrypt** [comment] 2017-12-29 08:59
for that feature you need to start the miner two times and give each a
different config.

**Comment by mojimi** [comment] 2017-12-29 19:25
I understand I can do that at the moment, but I assume is somewhat simple to implement, I would help if I knew anything about C

**Comment by fireice-uk** [comment] 2018-01-03 15:04
Closing as this is a duplicate of round-robin pools, already on the todo.

**Closed by fireice-uk** 2018-01-03 15:04 UTC
