### ISSUE TITLE
Please add pause/resume support in the miner

### ISSUE THREAD

**Issue by huserbg** [fireice-uk/xmr-stak#691] opened 2017-12-24 14:15 UTC
Hello,

I need pause/resume support (e.g. with the p key).
You may ask why I would need this as I can just exit and start the miner again.
However when I do this on my Windows laptop, the next time I try to start the miner, it usually fails to allocate large pages and the hashrate drops a lot. Then the only option is to restart Windows, which is very inconvenient.
If the miner can be paused without releasing the memory, this will no longer be a problem.

Regards!

**Comment by khel973** [comment] 2017-12-24 20:00
really need that to function from the web side. so a student can go to a server running this and pause it to give cpu cycles to video encoding and resume after. i don't want them to remote in to desktop

**Comment by fireice-uk** [comment] 2017-12-25 16:59
Closing as a duplicate of #145 - we are already working on it.

**Closed by fireice-uk** 2017-12-25 16:59 UTC

**Comment by justsonic** [comment] 2019-09-11 09:11
Good day!
Will the next releases include a pause mining feature? For example, by pressing the "p" key in the program window.
It is a very convenient function when the computer is used not only for mining, but also in everyday life.
