### ISSUE TITLE
feature request: pause

### ISSUE THREAD

**Issue by ndaman** [fireice-uk/xmr-stak#207] opened 2017-11-22 12:53 UTC
I think it would be great if there was a 'p' to pause option while running.

**Comment by rtzoeller** [comment] 2017-11-22 20:34
I plan on looking into implementing this over the next week or two

**Comment by fireice-uk** [comment] 2017-12-09 21:26
This is a duplicate of "idle detection" feature - we are working on it. Thanks for suggestion!

**Closed by fireice-uk** 2017-12-09 21:26 UTC
