### ISSUE TITLE
XMR-STAK cannot utilize 10MB L3 cache on a Xeon E5-1620 V2

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [fireice-uk/xmr-stak#952] opened 2018-01-23 00:44 UTC
As the title says I have Dell T3610 Windows 10 systems with a Xeon E5-1620 V2 in them. The  Xeon E5-1620 V2 has 10MB of L3 cache.

http://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%20E5-1620%20v2.html

I have tried various configuration settings in the CPU.txt file but any time I try to use the 10MB L3 cache (5 threads) the hash rate drops down to what I was having with 4 threads.

My understanding (and actual results) is that each thread uses 2MB of cache so 5 threads would be optimal.

With 4 threads and using in a (3-core 1x, 1x, 2x) or (2-core 2x, 2x) configurations gives me 261 H/s and 245 H/s.

When I try 5 thread (3-core 1x, 2x, 2x) or a (2-core 2x, 3x)  configurations I only get 259 H/s which is basically the same as using 4 threads.

I am not getting any errors in the XMR-STAK program screen log just getting reduced hash rate for each core if I try to use 5 threads. I do see the proper number of threads are started in the screen log.

4 thread configurations:

        { "low_power_mode" : 1,  "no_prefetch" : true, "affine_to_cpu" : 2  }, 
        { "low_power_mode" : 1,  "no_prefetch" : true, "affine_to_cpu" : 4  },
        { "low_power_mode" : 2,  "no_prefetch" : true, "affine_to_cpu" : 6  },

or

        { "low_power_mode" : 2,  "no_prefetch" : true, "affine_to_cpu" : 4  },
        { "low_power_mode" : 2,  "no_prefetch" : true, "affine_to_cpu" : 6  },

5 thread configurations:

        { "low_power_mode" : 1,  "no_prefetch" : true, "affine_to_cpu" : 2  }, 
        { "low_power_mode" : 2,  "no_prefetch" : true, "affine_to_cpu" : 4  },
        { "low_power_mode" : 2,  "no_prefetch" : true, "affine_to_cpu" : 6  },

or

        { "low_power_mode" : 2,  "no_prefetch" : true, "affine_to_cpu" : 4  },
        { "low_power_mode" : 3,  "no_prefetch" : true, "affine_to_cpu" : 6  },

**Comment by nomadsa** [comment] 2018-01-24 07:21
I have a similar issue. It ignores directives for "cpu_threads_conf".

**Comment by kio3i0j9024vkoenio** [comment] 2018-01-24 17:40
I do not see it ignoring directives. The following shows six configurations and runs on the Dell T3610 with a Xeon E5-1620 V2 that has 10MB L3 cache. In each of the runs I can see the proper number of threads starting. The problem is that XMR-Stak seems to treat 5 threads (258 H/s) the same a 4 threads (259 H/s) even though 5 threads should fit just fine in the 10MB L3 cache. 

4 threads configurations:

1x, 1x, 2x produced 259 H/s
2x, 2x produced 243 H/s
4x produced 200 H/s

4 threads configurations:

1x, 2x, 2x produced 258 H/s
2x, 3x produced 232 H/s
5x produced 173 H/s

Full details of runs are in attached file.

[XMR-Stak on E5-1620 V2 Results.txt](https://github.com/fireice-uk/xmr-stak/files/1660937/XMR-Stak.on.E5-1620.V2.Results.txt)

**Comment by mvpel** [comment] 2018-01-26 06:01
Don't forget that in order to fetch work from and send results to the pool, the operating system needs some memory too. And with five threads using 2MB of CryptoNight scratchpad space each, any other process on the system will be required to displace at least one of the miners' scratchpads from L3 cache, and it will have to be fetched again from the DIMMs as soon as the TCP packet is sent or what have you.

**Comment by JerichoJones** [comment] 2018-01-26 21:43
---
**_How-TO and tuning your hardware is not within the scope of Github support and will most likely be ignored.  It is just not possible for us to know how to tune every model/version of a component._**

_How-TO and tuning type questions are better suited to forums such as [REDDIT/r/moneromining](https://www.reddit.com/r/MoneroMining/new/).
There is a much larger audience of people that have probably already been through and resolved the same issue._

Make sure you have reviewed the [documentation](https://github.com/fireice-uk/xmr-stak/tree/master/doc) on the Github as well as running:
```
	xmr-stak --help
```
**^^ This will answer most How-TO type questions. ^^**

---

**Comment by kio3i0j9024vkoenio** [comment] 2018-01-26 23:40
This problem is a BUG not a tuning issue.

Each thread is supposed to fit into 2MB of cache such that the optimal number of threads is L3 cache size divided by 2MB. Every article states that figure.

So 8MB L3 cache should use 4 threads and that does seem to work.

The BUG is that 10MB of L3 cache with 5 threads DOES NOT WORK as XMR-STAK seems to overflow the 10MB L3 cache and produce that same hash rate as 4 threads.

This should not happen.

**Comment by Simaex** [comment] 2018-01-27 09:14
No way the miner can be used without any OS overhead. If you fully utilise cache one scratchpad is discarded frequently resulting in poor performance, just as you describe. It is not a BUG, it's normal processor working procedure. The case was frequently discussed and is not the miner specific. Please reread HOW-TO for more details.

**Comment by kio3i0j9024vkoenio** [comment] 2018-01-28 22:24
You can bold the HOW-TO all you want. I am not a newbie that just got off the bus but an experienced programmer.

If I were to use your explanation the quad core E3-1270 that I am running on different machine that has 8MB L3 cache would not be able to use 4 threads because of the OS overhead. But yet it works just fine with 4T * ~2MB cache + OS overhead.

4T * ~2MB cache + OS overhead - Okay with 8MB cache

Somehow you are claiming that using one more thread on a 10MB L3 cache E5-1620 V3 would cause the OS to have much more overhead for that thread than what it uses for each of the first 4 threads.

5T * ~2MB cache + OS overhead - NOT Okay with 10MB cache

**Comment by fireice-uk** [comment] 2018-01-28 22:41
Please post the output of `xmr-stak.exe -V`

**Comment by kio3i0j9024vkoenio** [comment] 2018-01-29 04:00
Please post the output of xmr-stak.exe -V

Version: xmr-stak/2.2.0/c4400d19/master/win/nvidia-amd-cpu/aeon-monero/20

**Comment by fireice-uk** [comment] 2018-01-29 12:56
`This problem is a BUG not a tuning issue.`
`You can bold the HOW-TO all you want. I am not a newbie that just got off the bus but an experienced programmer.`

Closing as this is not a bug. The slowdown that you are seeing is due to 2 GPUs running on the system. My advice is to tune down the CPU slightly.

**Closed by fireice-uk** 2018-01-29 12:56 UTC
