### ISSUE TITLE
illegal instruction after cmake instruction

### ISSUE THREAD

**Issue by zoro10** [fireice-uk/xmr-stak#218] opened 2017-11-23 18:34 UTC
hi at all, I'm tryng to compile xmr-stack on fedora 27 but I have the result: 

`Illegal instruction (create core dump)`

any ideas ?
thanks for the response

**Comment by psychocrypt** [comment] 2017-11-23 18:53
Do you compiled the miner on a different system? Please check the
documentaion there is a flag to compile xmr-stak in generic mode.
XMR-STAK_COMPILE=generic

**Comment by psychocrypt** [comment] 2017-11-23 19:17
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile.md#generic-build-options

**Comment by zoro10** [comment] 2017-11-24 05:16
I have the error after the cmake command

**Comment by psychocrypt** [comment] 2017-11-24 07:30
Please provide pore information. Ppost the history of all comamnd you used
to compile xmr-stak and the full output of cmake within a empty build
folder.

**Comment by zoro10** [comment] 2017-11-24 20:07
that's the error:

`[andrea@localhost xmr-stak]$ cmake
Illegal instruction (core dump creato)
`

**Comment by zoro10** [comment] 2017-11-25 12:41
no ideas?

**Comment by psychocrypt** [comment] 2017-11-25 13:01
Could you pleace try the current dev branch. We fixwed a few bugs maybe the
issue is already solved.

**Comment by fireice-uk** [comment] 2017-11-30 15:18
@zoro10 The issue is with your OS. Please try reinstalling. As it is cmake that is crashing and not the miner it is outside of our scope. I will close this issue.

**Closed by fireice-uk** 2017-11-30 15:18 UTC
