### ISSUE TITLE
Monero V7 POW Status

### ISSUE THREAD

**Issue by netmebtc** [fireice-uk/xmr-stak#1163] opened 2018-03-16 12:28 UTC

**Comment by sferoze** [comment] 2018-03-16 20:36
@netmebtc seems like the hard fork is in 11 days according to http://xmr.noctism.com

So we will need to run new mining software or an update to use the new POW. 

One thing that is confusing me, is since it is a hard fork... essentially we will have 2 monero coins? pre fork and after fork coins...

is this essentially doubling our monero coins? Or will the new hard fork coin use a new ticker symbol? How will this play out, I am confused.

**Comment by cdarken** [comment] 2018-03-16 21:53
@sferoze Probably won't be any or enough nodes to maintain the old protocol, but anybody that wants can stay and mine together with Bitmain's ASICS :grin:

**Comment by fireice-uk** [comment] 2018-03-17 13:36
I tried begging for an earlier release of the Monero binaries but they won't listen...

**Comment by jtgrassie** [comment] 2018-03-17 15:48
@fireice-uk 
> I tried begging for an earlier release of the Monero binaries but they won't listen...

Who / where did you beg? The PoW changes are already merged in the monero master branch so you can already pull, build and test. There is also a testnet up too.

**Comment by fireice-uk** [comment] 2018-03-18 01:47
@jtgrassie 

> Who / where did you beg?

Feel free to explain why 10 days before the fork, we don't have a final release version?

**Comment by jtgrassie** [comment] 2018-03-18 16:39
@fireice-uk https://github.com/monero-project/monero/issues/3427#issuecomment-374000367
>The fork was pushed to the 6th for that reason (1546000). The need to add mitigations for the key reusing fork pushed a lot of work needing doing for the release too. Ah well. Maybe next time will be on time.

Further, you do have a PR for the PoW change as submitted by @vtnerd #1126 which as I understand it is the only thing that affects xmr-stak with regards to the monero HF release. Other monero changes do not directly affect mining.

This all said, anyone who wishes to fork xmr-stak and merge #1126 then build can of course do themselves. No need to wait if anyone want's to test now.

**Comment by bobbieltd** [comment] 2018-03-18 17:37
@jtgrassie Sorry, I don’t understand. What is wrong with that PR ? If it’s OK, xmr-stak can merge it. Copyright issue or some thing else ?

**Comment by psychocrypt** [comment] 2018-03-18 17:43
We need to take care that other coins will still be mineable. Please give
us some more days.

**Comment by jtgrassie** [comment] 2018-03-18 18:45
@bobbieltd There's nothing "wrong" with the PR at all.

@psychocrypt Absolutely understand your position. 

I'll repeat to everyone asking for an early release: If anyone wants this **now** to test, pull master, merge the PR, build and test. If you would rather have an official xmr-stak release, you have to wait as the team need to test themselves.

**Comment by fireice-uk** [comment] 2018-03-18 20:15
@jtgrassie you don't even need to fork, clone, cherry pick the pr and you are good to go.

I don't like to fly by the seat of my pants. In normal software development we have dev branches, release candidates and feature freezes. Don't take out Monero's mess on me please.

**Comment by jtgrassie** [comment] 2018-03-18 22:18
@fireice-uk
> you don't even need to fork, clone, cherry pick the pr and you are good to go. If it works. 

I never suggested anyone need to fork. Just clone the repo and merge the PR, build and run.

> As is it will certainly break ETN, not sure about other stuff.

I never said it wouldn't break anything else. Just if people needed to test the new Monero PoW there was an easy way. You seemed to miss the word "test" I used. And let's be clear here, @vtnerd created a comprehensive PR to _help_ you. There are some in the community that wish to test, again to _help_ you.

> I don't like to fly by the seat of my pants. In normal software development we have dev branches, release candidates and feature freezes. Don't take out Monero's mess on me please.

Wow. 1. I don't see a Monero mess as you put it. 2.  What have I taken out on you? Nothing. The OP was asking for something to _test_. In fact, if anything, I have been trying to help you by letting people know how they can test before you do a release. Really not understanding your hostility here.

**Comment by jtgrassie** [comment] 2018-03-18 22:33
@fireice-uk 
> As is it will certainly break ETN, not sure about other stuff.

Yes it will certainly break mining of Monero forks that do not also update their PoW to the same as Monero. Bottom line is this: if you want to support Monero mining you have to implement the change to the PoW. If you want to support the forks, you have to implement their current PoW too. Some of the forks have already stated they will be following Monero's PoW, though not at the same time. That of course means that if you want to support all the coins you currently support, you need to ensure the software supports multiple versions of the PoW. You know this, I know this and yes it's a pain, but it not Monero's fault they wish to remain ASIC resistant. You can also choose to drop Monero mining if it is annoying you this much. Someone will just then fork xmr-stak and implement the new monero PoW.

But listen, I do understand this is frustrating, but it's hugely important WRT decentralization. The very people using xmr-stak would be marginalized by ASIC producers without this change.

**Comment by psychocrypt** [comment] 2018-03-18 22:46
Again don't worry. @fireice-uk and me implementing the last changes. We
will support all current coins and the new monero pow.
And yes it was very nice that @vtnerd provide a patch for the pow change to
xmr-stak.

**Comment by netmebtc** [comment] 2018-03-19 01:02
Thank you @fireice-uk @psychocrypt very much   for your hard working !
and thank you @jtgrassie for giving so much  good suggestion.

All cpu and gpu miners thank you too.

**Comment by fireice-uk** [comment] 2018-03-19 08:46
@jtgrassie 

> And let's be clear here, @vtnerd created a comprehensive PR to help you. There are some in the community that wish to test, again to help you.

If that's the intent then you certainly have a _unique_ way of going about it. 

> I beg for you to release the xmr-stak. that supports Monero V7 POW as soon as possible

> netmebtc changed the title from About shit tag of Monero V7 release to About tag of Monero V7 release a day ago

> Who / where did you beg? 

While at this point I'm fairly used to all kinds of wild-eyed crazy coming out of Monero's woodwork, it doesn't make it any less depressing.

**Comment by jtgrassie** [comment] 2018-03-19 17:49
@fireice-uk 

OP title as seen above:
**Monero V7 POW Testing pool**

> wild-eyed crazy coming out of Monero's woodwork

Seriously? I am honestly really surprised by your tone. xmr-stak is a miner made for originally mining Monero (XMR). Because some other coins have forked from Monero, people have also been able to mine those forks xmr-stak. Monero requires a PoW change due to ASICs and you _appear_ (at least to me) to be bad mouthing the Monero community / devs now. Hope I am misreading!

**Comment by fireice-uk** [comment] 2018-03-19 18:28
> Monero requires a PoW change due to ASICs and you appear (at least to me) to be bad mouthing the Monero community / devs now. Hope I am misreading!

Yes you are misreading, mostly by projecting the developer's "we are the community" attitude. I don't treat Monero community as a single entity.

**Comment by jtgrassie** [comment] 2018-03-19 19:05
> Yes you are misreading

Good.

> wild-eyed crazy coming out of Monero's woodwork

> Don't take out Monero's mess on me please.

> I tried begging for an earlier release of the Monero binaries but they won't listen...

Because those things all sound like pretty negative things to be saying about Monero.

**Comment by fireice-uk** [comment] 2018-03-19 19:26
Again, Monero community != Monero != Monero developers. 

When I say "Monero development is a total mess. Never mind industry practices like dev branches. It is ran by a guy who barely understands git and avoids branch merges like a fire." I'm talking about Monero developers.

When I have a guy who is swearing at me about a release of a FOSS software, again, I'm commenting on certain sections of the community, not it as a whole.

**Comment by jtgrassie** [comment] 2018-03-19 20:05
> Never mind industry practices like dev branches. It is ran by a guy who barely understands git and avoids branch merges like a fire." I'm talking about Monero developers. (By the way please let him know that he only needs to type git checkout release-v0.12; git merge master; git push there is no need to open separate PRs with the same thing to two branches)

Well there are a lot of developers and there IS an agreed branch process. PR's are feature branches that get merged to master cleanly once they have been peer reviewed. As for releases, these are branched off master to a release branch when master is deemed to be a release. Due to the 6 month HF, these have to be carefully coordinated due to the hardcoded fork block height. Hence why the release branch is created ahead of time to coordinate testing and rebasing and last minute PRs to master. 

>  It is ran by a guy 

it is not run by a guy. It's a whole group of people who come to agreement.

> who barely understands git 

And you know that how? LOL

> When I have a guy who is swearing at me about a release of a FOSS software

Where and who is swearing at you? I've not seen this.

**Comment by fireice-uk** [comment] 2018-03-19 20:14
> It is ran by a guy who barely understands git and avoids branch merges like a fire." I'm talking about Monero developers. (By the way please let him know that he only needs to type git checkout release-v0.12; git merge master; git push there is no need to open separate PRs with the same thing to two branches)

> And you know that how? LOL
> Well there are a lot of developers and there IS an agreed branch process.  [ ... cut a paragraph of technical razzle-dazzle attempt ... ]

https://github.com/monero-project/monero/pull/3434
https://github.com/monero-project/monero/pull/3441

https://github.com/monero-project/monero/pull/3431
https://github.com/monero-project/monero/pull/3432

As I said, plase explain to him that the proper commands to use in this situation are `git checkout release-v0.12; git merge master; git push` There is no need to make contributors open two separate PRs.

> Where and who is swearing at you? I've not seen this.

You haven't read my reply to you above then, here is, again, quote from OP that you are so valiantly defending.

> I have beg them for that shit release. What you can't do, I do it for you [1](https://github.com/fireice-uk/xmr-stak/issues/1160#issuecomment-373967083)

**Comment by jtgrassie** [comment] 2018-03-19 20:31
All _agreed_ and _documented_:
https://github.com/monero-project/monero/blob/master/README.md 
See section "Scheduled mandatory software upgrades"

And contribution (coding style, branches, PRs etc):
https://github.com/monero-project/monero/blob/master/CONTRIBUTING.md

> You haven't read my reply to you above then, here is, again, quote from OP that you are so valiantly defending.
>>I have beg them for that shit release. What you can't do, I do it for you 

That was never the title of this issue, as you have claimed. This issue does not how anything to say the title has changed. Which is what it would if the title had been edited. What you are linking to is a different issue by an _xmr-stak_ user. I wholeheartedly agree it's a shame one of the users of a FOSS project you maintain speaks like that. I hope it was simply a spelling mistake or it may not even have been directed at you personally.

Unfortunately, the way you are talking to me and about @fluffypony, kind of falls into the very same category you are complaining about! 

Anyway, scincerely, good luck with the changes. Hope the comprehensive PR @vtnerd made was helpful. Hope the Monero developers have helped keep xmr-stak relevant by continuing to be ASIC resistant.

**Comment by fluffypony** [comment] 2018-03-19 21:09
@fireice-uk separate PRs are necessary as the code doesn’t always apply in the same way as master deviates, and also because a PR to master may require different discussion than a PR to the branch. It’s important to have a record both for why something is merged, and/or for why it’s rejected. Do you not agree that this approach, whilst requiring extra effort, provides the maximal amount of information and historical record?

To your points, in general - everyone is aware of how tight this fork is. When we wanted to branch in December, nobody expected the Bulletproofs uncertainty and the general frustration with Monero’s fees, and that forces us to use a bit of leeway with the release. When the ASIC situation appeared in February we realised the very dire security situation. ASICs could be used to create hard to verify blocks that could DoS ordinary nodes! Surely that’s a situation that needs averting, even if the timelines are tight?

I’m truly sorry that I, and the rest of the Monero developers and community, have not lived up to your high expectations. We are doing our best to steward and build a complex piece of open-source software, whilst having to make hard decisions as a group. It saddens me that someone of your expertise refuses to participate in those discussions out of spite. But suffice it to say that we are trying our best, and it is disappointing to me that we have failed you as a contributor and member of the community. We will continue to try harder and to do better, and we appreciate your steady and constant stream of open and public criticism.

**Comment by fireice-uk** [comment] 2018-03-19 23:56
If I don't talk to you, it is out of spite. If I talk to you it is passive aggressive. Anyone who doesn't shower you with praise? An attack on Monero!!!!

Ethereum? SCAM!!!111!! Open source/GPL? MALICIOUS!!!!!111!!!  Anything else you don't like? SCAM SCAM SCAM!!!!!

Perhaps the problem is in your mindset here.

**Comment by netmebtc** [comment] 2018-03-20 04:34
@fireice-uk  dear @fireice-uk  and @psychocrypt , The  Monero release-v0.12 branch is now on github:  https://github.com/monero-project/monero/tree/release-v0.12. Hope this release can improve your dev of new version.

**Comment by fireice-uk** [comment] 2018-03-20 15:57
I would expect a release somewhere around this weekend.

**Comment by aleqx** [comment] 2018-03-22 19:09
High school drama aside (always a nice reminder why serious people still don't take crypto seriously), I must say the xmr-stak code is quite high quality and I hope xmr-stak will have a release for the masses before March 28th. To whoever kept suggesting it: please stop telling people that they should pull, patch and build themselves if you want wider adoption ... that mentality is part of the general problem. Also please find a way to work with (not against) each other. It looks petty from both sides and risks attracting a similar audience.

p.s. xmrig has published their updated version that supports V7. Incentives :P

**Closed** 2018-03-31 11:03 UTC
