### ISSUE TITLE
"Share above target" version 2.3.0 monero-7 (Nicehash)

### ISSUE THREAD

**Issue by DrStein99** [fireice-uk/xmr-stak#1222] opened 2018-03-26 22:32 UTC
(on "MONERO7" setting)

I compiled version 2.3.0, and run on 2 of my rigs.  Runs flawless on monero pools.  I test one rig to Nicehash.  Immediately starts rejecting shares "Share above target".  

I restart the rig, try again - and the errors come right in.  I try on 1 more additional rig test and results are the same.

After 1 hour hashing both rigs, so far it's reporting 91% and 93% (but I am not sure since Nicehash does "socket closed" and the STATS become offset by it's 90 second break-time to mine another pool between Nicehash socket-closings).

I guess they have not switched to Monero7, or some other reason - I do not know.

**Comment by Sandown** [comment] 2018-03-28 17:52
Same issue here, reports miner errors within stak. 

for example:

[stratum+tcp://cryptonightv7.eu.nicehash.com:3363] PARSE error: Unsupported server method mining.set_extranonce
--

**Comment by DrStein99** [comment] 2018-03-29 16:53
I was connecting to cryptonight stratum server.  I did not use cryptonightv7.eu.nicehash.com.  But now that I know that it exists, I will try again, and use the cryptonight7 setting to re-test.

**Comment by Sigura** [comment] 2018-03-29 21:43
looks like a same as I got for 2.3.0 monero7:

{"version":"xmr-stak/2.3.0/a036cd81/unknown/win/nvidia-amd-cpu/aeon-cryptonight-monero/0","hashrate":{"threads":[[null,438.0,907.8],[null,430.8,908.5],[null,401.2,852.9],[null,406.7,856.1],[null,432.3,906.1],[null,439.9,907.0],[null,431.3,882.8],[null,404.5,879.7],[null,438.3,929.3],[null,462.9,930.4],[null,465.6,936.1],[null,441.1,937.1],[null,438.3,929.6],[null,465.8,932.8],[null,463.3,922.3],[null,437.4,921.4],[70.9,31.8,65.5],[73.2,32.8,67.5],[71.9,32.2,66.7],[70.6,31.7,65.5]],"total":[null,7126.0,14805.1],"highest":16229.5},"results":{"diff_current":200007,"shares_good":4,"shares_total":229,"avg_time":0.0,"hashes_total":0,"best":[1007897,638109,402073,234213,0,0,0,0,0,0],"error_log":[{"count":31,"last_seen":1522301269,"text":"Share above target."},{"count":27,"last_seen":1522301882,"text":"AMD Invalid Result GPU ID 5"},{"count":27,"last_seen":1522301916,"text":"AMD Invalid Result GPU ID 4"},{"count":25,"last_seen":1522301918,"text":"AMD Invalid Result GPU ID 1"},{"count":28,"last_seen":1522301715,"text":"AMD Invalid Result GPU ID 7"},{"count":17,"last_seen":1522301545,"text":"AMD Invalid Result GPU ID 6"},{"count":22,"last_seen":1522301833,"text":"AMD Invalid Result GPU ID 3"},{"count":27,"last_seen":1522301544,"text":"AMD Invalid Result GPU ID 2"},{"count":20,"last_seen":1522301672,"text":"AMD Invalid Result GPU ID 0"},{"count":1,"last_seen":1522301202,"text":"Job not found."}]},"connection":{"pool": "cryptonight.eu.nicehash.com:3355","uptime":3,"ping":0,"error_log":[{"last_seen":1522300472,"text":"[cryptonight.eu.nicehash.com:3355] RECEIVE error: socket closed"},{"last_seen":1522301269,"text":"[cryptonight.eu.nicehash.com:3355] RECEIVE error: socket closed"}]}}
2018-03-29_08:40    Restarting after 50 Min - Hash rate dropped from 15913.9 H/s to  H/s
2018-03-29_08:40    Script Ended


OS: win10x64, 8xVega56

all is fine on 2.2

**Comment by DrStein99** [comment] 2018-03-30 03:01
I keep getting:

` SOCKET ERROR - [stratum+tcp://cryptonightv7.eu.nicehash.com:3363] PARSE error: Unsupported server method mining.set_extranonce`

I am not getting it (so far) on my other rig, with identical hardware - which is connected to (PORT 3355):

`stratum+tcp://cryptonightv7.br.nicehash.com:3355`

**Comment by psychocrypt** [comment] 2018-03-30 06:18
Nicehash used a non standard way to change the nonce. It looks like this
isnow required.

@fireice_uk It looks like nicehash is now assuming that monero7 miner
support set_extranonce :-(

**Comment by Sigura** [comment] 2018-03-30 13:05
@psychocrypt I think you are mean @fireice-uk

**Comment by psychocrypt** [comment] 2018-03-30 13:20
thx for the correction I used the autocorrection of my smartphone.

**Comment by Sigura** [comment] 2018-03-30 14:00
np, `xmr-stak` is the awesome product!

**Comment by fireice-uk** [comment] 2018-03-31 10:28
Thanks! I wish that they would get their software in decent working order someday...

**Comment by Sigura** [comment] 2018-04-01 15:13
@xmrig @fireice-uk  Maybe exists a way to decrease impact?

**Comment by randelsr** [comment] 2018-04-05 15:44
@fireice-uk @psychocrypt I also receive these errors when using xmr-stak 2.3, Nicehash, monero7

SOCKET ERROR - [stratum+tcp://cryptonightv7.eu.nicehash.com:3363] PARSE error: Unsupported server method mining.set_extranonce

However, I am finding valid shares, but it's constantly switching between pools (usa vs eu nicehash)

Please advise

**Comment by psychocrypt** [comment] 2018-04-05 17:46
Do not use nicehash is the simplest solution ;-)
The problem is the nicehash pool, you need to open an ticket there. All
other pools are working without any issues only the shitty nicehash
software is not working.
Never the less we will look into it but not with high priority  This
behaviour is old and nicehash needs to fix the pool software.

**Comment by randelsr** [comment] 2018-04-05 17:48
@psychocrypt Thanks. I rec'd this back from NiceHash team:

We are aware of the problem and we already found a solution. Everything will be fixed this evening or tomorrow early in the morning.

Thank you for understanding.

Kind regards,
NiceHash Team

**Comment by psychocrypt** [comment] 2018-04-05 17:54
Thanks for forwarding.

**Comment by DrStein99** [comment] 2018-04-05 18:55
I am willing to NOT use Nicehash.  I have entertained other options - using xmr/monero.  If anyone can suggest where to point my hashing rigs to a more profitable solution - I would enjoy entertaining that option.

----

In the meantime.....  I actually setup a rig to run over-night WRONG by accident, as "MONERO7" & connecting to Nicehash cryptonight pool.  It actually ran all night long, and returned the SAME extranonce errors as it did when I ran the same machine setup as "monero7" on their actual Monero7 pool.

**Comment by Sigura** [comment] 2018-04-06 12:08
Got replay:

> Hello!
> 
> We are aware of the problem and we already found a solution. Everything will be fixed today evening or tomorrow early in the morning.
> 
> Thank you for understanding.
> 
> Kind regards,
> NiceHash Team

![screen shot 2018-04-06 at 15 05 13](https://user-images.githubusercontent.com/428500/38420328-04ee62a8-39ac-11e8-9245-a62381450710.png)

**Comment by DrStein99** [comment] 2018-04-06 12:40
Did anyone else here absolutely lose 100% of all their BCN on Nicehash while testing to mine on monero7?  I did.  Thanks Nicehash, I guess I will be expecting payment for that 6 months from now when BCN lowers to $2,000 / usd.

**Comment by hchan123** [comment] 2018-04-06 12:58
Started getting above target shares again. :(

**Comment by psychocrypt** [comment] 2018-05-01 19:43
maybe #1526 is solving the nicehash issue

**Closed** 2018-06-11 23:48 UTC
